spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGO_DB_CONNECTION_STRING}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      password: ${REDIS_PASSWORD}
server:
  port: ${SERVER_PORT}
url:
  user-service: ${USER_SERVICE_HOST}
  product-service: ${PRODUCT_SERVICE_HOST}

kafka:
  servers: ${KAFKA_SERVERS}
